# -*- coding: utf-8 -*-
"""001.hair_output.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fxokIAK1zf8bFoT0Re85uaNf52sM1cYU
"""

# 모듈 import
from tensorflow.keras import models
import cv2
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
import matplotlib.image as image

# output 함수

def hair_output(model, filename, img_size):
  labels = ['리젠트','리프', '바디', '보니', '보브', '빌드', '소프트투블럭댄디', '숏단발', '쉐도우', 
            '에어', '원랭스','플리츠', '허쉬', '히피','기타스타일']  #class 15

  for file in filename: ## 학습 이미지 사이즈 256* 256
    img = image.imread(file)
    img_ = img[:, :, :3]
    img = cv2.resize(img_, (img_size, img_size))
    img = img.reshape(1, img_size, img_size, 3)
    pred = model.predict(img)[0]
    maxidx = np.argmax(pred)

    # output을 500*500으로 할 경우
    output_img = cv2.resize(img_, (500, 500))
    plt.imshow(output_img)
    # plt.title(f"{labels[maxidx]}")
    plt.show()
    
    print('>>> your hairstyle is ',f"{labels[maxidx]}")

    return f"{labels[maxidx]}"

model = models.load_model('./hair_class15_ver1.h5')
filename = glob('./33.png')

#output 불러오느 코드
hair_output(model, filename,256)