# -*- coding: utf-8 -*-
"""001.length_output.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F21LD_DptkFh8xQit3XHs9OBDw-ZfsUc
"""

from tensorflow.keras import models
import cv2
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
import matplotlib.image as image

# output 함수

def length_output(model, filename, img_size):
  labels = ['남자', '단발', '여숏', '장발', '중발']  #class 5

  for file in filename: ## 학습 이미지 사이즈 256* 256
    img = image.imread(file)
    img_ = img[:, :, :3]
    img = cv2.resize(img_, (img_size, img_size))
    img = img.reshape(1, img_size, img_size, 3)
    pred = model.predict(img)[0]
    maxidx = np.argmax(pred)

    # output을 500*500으로 할 경우
    output_img = cv2.resize(img_, (500, 500))
    plt.imshow(output_img)
    # plt.title(f"{labels[maxidx]}")
    plt.show()
    
    print('>>> your hair length is ',f"{labels[maxidx]}")

    return f"{labels[maxidx]}"

model = models.load_model('./hair_length_class5_ver1.h5')

filename = glob('./sample_img/33.png')

#output 불러오는 코드
length_output(model, filename, 256)